lynxdtn01:
   one-to-many:
    0 :
      core: 0
      port: 6000
    1 :
      core: 1
      port: 6001
    2 :
      core: 2
      port: 6002
    3 :
      core: 3
      port: 6003
    4 :
      core: 4
      port: 6004
    5 :
      core: 5
      port: 6005
    6 :
      core: 6
      port: 6006
    7 :
      core: 7
      port: 6007
    8 :
      core: 8
      port: 6008
    9 :
      core: 9
      port: 6009
    10 :
      core: 10
      port: 6010
    11 :
      core: 11
      port: 6011
    12 :
      core: 12
      port: 6012
    13 :
      core: 13
      port: 6013
    14 :
      core: 14
      port: 6014
    15 :
      core: 15
      port: 6015
    16 :
      core: 0
      port: 6016
    17 :
      core: 1
      port: 6017
    18 :
      core: 2
      port: 6018
    19 :
      core: 3
      port: 6019
    20 :
      core: 4
      port: 6020
    21 :
      core: 5
      port: 6021
    22 :
      core: 6
      port: 6022
    23 :
      core: 7
      port: 6023
    24 :
      core: 8
      port: 6024
    25 :
      core: 9
      port: 6025
    26 :
      core: 10
      port: 6026
    27 :
      core: 11
      port: 6027
    28 :
      core: 12
      port: 6028
    29 :
      core: 13
      port: 6029
    30 :
      core: 14
      port: 6030
    31 :
      core: 15
      port: 6031
    32 :
      core: 16
      port: 6032
    33 :
      core: 17
      port: 6033
    34 :
      core: 18
      port: 6034
    35 :
      core: 19
      port: 6035
    36 :
      core: 20
      port: 6036
    37 :
      core: 21
      port: 6037
    38 :
      core: 22
      port: 6038
    39 :
      core: 23
      port: 6039
    40 :
      core: 24
      port: 6040
    41 :
      core: 25
      port: 6041
    42 :
      core: 26
      port: 6042
    43 :
      core: 27
      port: 6043
    44 :
      core: 28
      port: 6044
    45 :
      core: 29
      port: 6045
    46 :
      core: 30
      port: 6046
    47 :
      core: 31
      port: 6047
    48 :
      core: 16
      port: 6048
    49 :
      core: 17
      port: 6049
    50 :
      core: 18
      port: 6050
    51 :
      core: 19
      port: 6051
    52 :
      core: 20
      port: 6052
    53 :
      core: 21
      port: 6053
    54 :
      core: 22
      port: 6054
    55 :
      core: 23
      port: 6055
    56 :
      core: 24
      port: 6056
    57 :
      core: 25
      port: 6057
    58 :
      core: 26
      port: 6058
    59 :
      core: 27
      port: 6059
    60 :
      core: 28
      port: 6060
    61 :
      core: 29
      port: 6061
    62 :
      core: 30
      port: 6062
    63 :
      core: 31
      port: 6063
polaris-login1:
   one-to-many:
    0 :
      core: 0
      port: 6000
    1 :
      core: 1
      port: 6001
    2 :
      core: 2
      port: 6002
    3 :
      core: 3
      port: 6003
    4 :
      core: 4
      port: 6004
    5 :
      core: 5
      port: 6005
    6 :
      core: 6
      port: 6006
    7 :
      core: 7
      port: 6007
    8 :
      core: 8
      port: 6008
    9 :
      core: 9
      port: 6009
    10 :
      core: 10
      port: 6010
    11 :
      core: 11
      port: 6011
    12 :
      core: 12
      port: 6012
    13 :
      core: 13
      port: 6013
    14 :
      core: 14
      port: 6014
    15 :
      core: 15
      port: 6015
    16 :
      core: 16
      port: 6016
    17 :
      core: 17
      port: 6017
    18 :
      core: 18
      port: 6018
    19 :
      core: 19
      port: 6019
    20 :
      core: 20
      port: 6020
    21 :
      core: 21
      port: 6021
    22 :
      core: 22
      port: 6022
    23 :
      core: 23
      port: 6023
    24 :
      core: 24
      port: 6024
    25 :
      core: 25
      port: 6025
    26 :
      core: 26
      port: 6026
    27 :
      core: 27
      port: 6027
    28 :
      core: 28
      port: 6028
    29 :
      core: 29
      port: 6029
    30 :
      core: 30
      port: 6030
    31 :
      core: 31
      port: 6031
polaris-login2:
   one-to-many:
    0 :
      core: 0
      port: 6032
    1 :
      core: 1
      port: 6033
    2 :
      core: 2
      port: 6034
    3 :
      core: 3
      port: 6035
    4 :
      core: 4
      port: 6036
    5 :
      core: 5
      port: 6037
    6 :
      core: 6
      port: 6038
    7 :
      core: 7
      port: 6039
    8 :
      core: 8
      port: 6040
    9 :
      core: 9
      port: 6041
    10 :
      core: 10
      port: 6042
    11 :
      core: 11
      port: 6043
    12 :
      core: 12
      port: 6044
    13 :
      core: 13
      port: 6045
    14 :
      core: 14
      port: 6046
    15 :
      core: 15
      port: 6047
    16 :
      core: 16
      port: 6048
    17 :
      core: 17
      port: 6049
    18 :
      core: 18
      port: 6050
    19 :
      core: 19
      port: 6051
    20 :
      core: 20
      port: 6052
    21 :
      core: 21
      port: 6053
    22 :
      core: 22
      port: 6054
    23 :
      core: 23
      port: 6055
    24 :
      core: 24
      port: 6056
    25 :
      core: 25
      port: 6057
    26 :
      core: 26
      port: 6058
    27 :
      core: 27
      port: 6059
    28 :
      core: 28
      port: 6060
    29 :
      core: 29
      port: 6061
    30 :
      core: 30
      port: 6062
    31 :
      core: 31
      port: 6063
