OS:
   OS:
    0 :
      port: 6000
    1 :
      port: 6001
    2 :
      port: 6002
    3 :
      port: 6003
    4 :
      port: 6004
    5 :
      port: 6005
    6 :
      port: 6006
    7 :
      port: 6007
    8 :
      port: 6008
    9 :
      port: 6009
    10 :
      port: 6010
    11 :
      port: 6011
    12 :
      port: 6012
    13 :
      port: 6013
    14 :
      port: 6014
    15 :
      port: 6015
    16 :
      port: 6016
    17 :
      port: 6017
    18 :
      port: 6018
    19 :
      port: 6019
    20 :
      port: 6020
    21 :
      port: 6021
    22 :
      port: 6022
    23 :
      port: 6023
    24 :
      port: 6024
    25 :
      port: 6025
    26 :
      port: 6026
    27 :
      port: 6027
    28 :
      port: 6028
    29 :
      port: 6029
    30 :
      port: 6030
    31 :
      port: 6031
NUMA0:
   NUMA0:
    0 :
      core1: 0
      port: 6000
    1 :
      core1: 1
      port: 6001
    2 :
      core1: 2
      port: 6002
    3 :
      core1: 3
      port: 6003
    4 :
      core1: 4
      port: 6004
    5 :
      core1: 5
      port: 6005
    6 :
      core1: 6
      port: 6006
    7 :
      core1: 7
      port: 6007
    8 :
      core1: 8
      port: 6008
    9 :
      core1: 9
      port: 6009
    10 :
      core1: 10
      port: 6010
    11 :
      core1: 11
      port: 6011
    12 :
      core1: 12
      port: 6012
    13 :
      core1: 13
      port: 6013
    14 :
      core1: 14
      port: 6014
    15 :
      core1: 15
      port: 6015
    16 :
      core1: 0
      port: 6016
    17 :
      core1: 1
      port: 6017
    18 :
      core1: 2
      port: 6018
    19 :
      core1: 3
      port: 6019
    20 :
      core1: 4
      port: 6020
    21 :
      core1: 5
      port: 6021
    22 :
      core1: 6
      port: 6022
    23 :
      core1: 7
      port: 6023
    24 :
      core1: 8
      port: 6024
    25 :
      core1: 9
      port: 6025
    26 :
      core1: 10
      port: 6026
    27 :
      core1: 11
      port: 6027
    28 :
      core1: 12
      port: 6028
    29 :
      core1: 13
      port: 6029
    30 :
      core1: 14
      port: 6030
    31 :
      core1: 15
      port: 6031
NUMA1:
   NUMA1:
    0 :
      core1: 16
      port: 6000
    1 :
      core1: 17
      port: 6001
    2 :
      core1: 18
      port: 6002
    3 :
      core1: 19
      port: 6003
    4 :
      core1: 20
      port: 6004
    5 :
      core1: 21
      port: 6005
    6 :
      core1: 22
      port: 6006
    7 :
      core1: 23
      port: 6007
    8 :
      core1: 24
      port: 6008
    9 :
      core1: 25
      port: 6009
    10 :
      core1: 26
      port: 6010
    11 :
      core1: 27
      port: 6011
    12 :
      core1: 28
      port: 6012
    13 :
      core1: 29
      port: 6013
    14 :
      core1: 30
      port: 6014
    15 :
      core1: 31
      port: 6015
    16 :
      core1: 16
      port: 6016
    17 :
      core1: 17
      port: 6017
    18 :
      core1: 18
      port: 6018
    19 :
      core1: 19
      port: 6019
    20 :
      core1: 20
      port: 6020
    21 :
      core1: 21
      port: 6021
    22 :
      core1: 22
      port: 6022
    23 :
      core1: 23
      port: 6023
    24 :
      core1: 24
      port: 6024
    25 :
      core1: 25
      port: 6025
    26 :
      core1: 26
      port: 6026
    27 :
      core1: 27
      port: 6027
    28 :
      core1: 28
      port: 6028
    29 :
      core1: 29
      port: 6029
    30 :
      core1: 30
      port: 6030
    31 :
      core1: 31
      port: 6031
NUMA0-2core:
   NUMA0-2core:
    0 :
      core1: 0
      core2: 1
      port: 6000
    1 :
      core1: 2
      core2: 3
      port: 6001
    2 :
      core1: 4
      core2: 5
      port: 6002
    3 :
      core1: 6
      core2: 7
      port: 6003
    4 :
      core1: 8
      core2: 9
      port: 6004
    5 :
      core1: 10
      core2: 11
      port: 6005
    6 :
      core1: 12
      core2: 13
      port: 6006
    7 :
      core1: 14
      core2: 15
      port: 6007
    8 :
      core1: 0
      core2: 1
      port: 6008
    9 :
      core1: 2
      core2: 3
      port: 6009
    10 :
      core1: 4
      core2: 5
      port: 6010
    11 :
      core1: 6
      core2: 7
      port: 6011
    12 :
      core1: 8
      core2: 9
      port: 6012
    13 :
      core1: 10
      core2: 11
      port: 6013
    14 :
      core1: 12
      core2: 13
      port: 6014
    15 :
      core1: 14
      core2: 15
      port: 6015
    16 :
      core1: 0
      core2: 1
      port: 6016
    17 :
      core1: 2
      core2: 3
      port: 6017
    18 :
      core1: 4
      core2: 5
      port: 6018
    19 :
      core1: 6
      core2: 7
      port: 6019
    20 :
      core1: 8
      core2: 9
      port: 6020
    21 :
      core1: 10
      core2: 11
      port: 6021
    22 :
      core1: 12
      core2: 13
      port: 6022
    23 :
      core1: 14
      core2: 15
      port: 6023
    24 :
      core1: 0
      core2: 1
      port: 6024
    25 :
      core1: 2
      core2: 3
      port: 6025
    26 :
      core1: 4
      core2: 5
      port: 6026
    27 :
      core1: 6
      core2: 7
      port: 6027
    28 :
      core1: 8
      core2: 9
      port: 6028
    29 :
      core1: 10
      core2: 11
      port: 6029
    30 :
      core1: 12
      core2: 13
      port: 6030
    31 :
      core1: 14
      core2: 15
      port: 6031
NUMA1-2core:
   NUMA1-2core:
    0 :
      core1: 16
      core2: 17
      port: 6000
    1 :
      core1: 18
      core2: 19
      port: 6001
    2 :
      core1: 20
      core2: 21
      port: 6002
    3 :
      core1: 22
      core2: 23
      port: 6003
    4 :
      core1: 24
      core2: 25
      port: 6004
    5 :
      core1: 26
      core2: 27
      port: 6005
    6 :
      core1: 28
      core2: 29
      port: 6006
    7 :
      core1: 30
      core2: 31
      port: 6007
    8 :
      core1: 16
      core2: 17
      port: 6008
    9 :
      core1: 18
      core2: 19
      port: 6009
    10 :
      core1: 20
      core2: 21
      port: 6010
    11 :
      core1: 22
      core2: 23
      port: 6011
    12 :
      core1: 24
      core2: 25
      port: 6012
    13 :
      core1: 26
      core2: 27
      port: 6013
    14 :
      core1: 28
      core2: 29
      port: 6014
    15 :
      core1: 30
      core2: 31
      port: 6015
    16 :
      core1: 16
      core2: 17
      port: 6016
    17 :
      core1: 18
      core2: 19
      port: 6017
    18 :
      core1: 20
      core2: 21
      port: 6018
    19 :
      core1: 22
      core2: 23
      port: 6019
    20 :
      core1: 24
      core2: 25
      port: 6020
    21 :
      core1: 26
      core2: 27
      port: 6021
    22 :
      core1: 28
      core2: 29
      port: 6022
    23 :
      core1: 30
      core2: 31
      port: 6023
    24 :
      core1: 16
      core2: 17
      port: 6024
    25 :
      core1: 18
      core2: 19
      port: 6025
    26 :
      core1: 20
      core2: 21
      port: 6026
    27 :
      core1: 22
      core2: 23
      port: 6027
    28 :
      core1: 24
      core2: 25
      port: 6028
    29 :
      core1: 26
      core2: 27
      port: 6029
    30 :
      core1: 28
      core2: 29
      port: 6030
    31 :
      core1: 30
      core2: 31
      port: 6031
NUMA0,1-2core:
   NUMA0,1-2core:
    0 :
      core1: 0
      core2: 16
      port: 6000
    1 :
      core1: 1
      core2: 17
      port: 6001
    2 :
      core1: 2
      core2: 18
      port: 6002
    3 :
      core1: 3
      core2: 19
      port: 6003
    4 :
      core1: 4
      core2: 20
      port: 6004
    5 :
      core1: 5
      core2: 21
      port: 6005
    6 :
      core1: 6
      core2: 22
      port: 6006
    7 :
      core1: 7
      core2: 23
      port: 6007
    8 :
      core1: 8
      core2: 24
      port: 6008
    9 :
      core1: 9
      core2: 25
      port: 6009
    10 :
      core1: 10
      core2: 26
      port: 6010
    11 :
      core1: 11
      core2: 27
      port: 6011
    12 :
      core1: 12
      core2: 28
      port: 6012
    13 :
      core1: 13
      core2: 29
      port: 6013
    14 :
      core1: 14
      core2: 30
      port: 6014
    15 :
      core1: 15
      core2: 31
      port: 6015
    16 :
      core1: 0
      core2: 16
      port: 6016
    17 :
      core1: 1
      core2: 17
      port: 6017
    18 :
      core1: 2
      core2: 18
      port: 6018
    19 :
      core1: 3
      core2: 19
      port: 6019
    20 :
      core1: 4
      core2: 20
      port: 6020
    21 :
      core1: 5
      core2: 21
      port: 6021
    22 :
      core1: 6
      core2: 22
      port: 6022
    23 :
      core1: 7
      core2: 23
      port: 6023
    24 :
      core1: 8
      core2: 24
      port: 6024
    25 :
      core1: 9
      core2: 25
      port: 6025
    26 :
      core1: 10
      core2: 26
      port: 6026
    27 :
      core1: 11
      core2: 27
      port: 6027
    28 :
      core1: 12
      core2: 28
      port: 6028
    29 :
      core1: 13
      core2: 29
      port: 6029
    30 :
      core1: 14
      core2: 30
      port: 6030
    31 :
      core1: 15
      core2: 31
      port: 6031
polaris-login1:
   one-to-many:
    0 :
      port: 6000
    1 :
      port: 6001
    2 :
      port: 6002
    3 :
      port: 6003
    4 :
      port: 6004
    5 :
      port: 6005
    6 :
      port: 6006
    7 :
      port: 6007
polaris-login2:
   one-to-many:
    0 :
      port: 6008
    1 :
      port: 6009
    2 :
      port: 6010
    3 :
      port: 6011
    4 :
      port: 6012
    5 :
      port: 6013
    6 :
      port: 6014
    7 :
      port: 6015
polaris-login3:
   one-to-many:
    0 :
      port: 6016
    1 :
      port: 6017
    2 :
      port: 6018
    3 :
      port: 6019
    4 :
      port: 6020
    5 :
      port: 6021
    6 :
      port: 6022
    7 :
      port: 6023
polaris-login4:
   one-to-many:
    0 :
      port: 6024
    1 :
      port: 6025
    2 :
      port: 6026
    3 :
      port: 6027
    4 :
      port: 6028
    5 :
      port: 6029
    6 :
      port: 6030
    7 :
      port: 6031
